config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "posts#index"

  resources :users, only: [:show, :edit, :update, :destroy]
  resources :friends, only: [:create, :destroy]
  resources :posts, only: [:index, :new, :create]

  resources :users do
    member do
      get :following, :followers
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  validates :follower_id, presence: true
  validates :followed_id, presence: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, dependent: :destroy

  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  has_many :active_friends, class_name: "Friend",
                            foreign_key: "follower_id",
                            dependent: :destroy
  has_many :passive_friends, class_name: "Friend",
                             foreign_key: "followed_id",
                             dependent: :destroy

  has_many :following, through: :active_friends, source: :followed
  has_many :followers, through: :passive_friends, source: :follower

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_friends.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  validates :name, presence: true
  validates :password, length: { minimum: 6 }, format: {with: /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i, message: "is invalid. Input half-width characters."}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_action :authenticate_user!, except: [:index]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  def create
    @user = User.find(params[:followed_id])
    current_user.follow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end

  def destroy
    @user = Friend.find(params[:id]).followed
    current_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end
  
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def post_params
    params.require(:post).permit(:content).merge(user_id: current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    if current_user.destroy(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers
    render 'show_follow'
  end

  private
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>index</h1>
<%= render "shared/header" %>


<% if user_signed_in? %>
  <%= link_to "投稿ページ", new_post_path %>
  <% @posts.each do |post|%>
    <div>
      <%= post.created_at %>
    </div>
    <div>
      <%= link_to post.user.name, user_path(post.user.id) %>
      <%= post.content %>
    </div>
  <% end %>
<% end %>

app/views/posts/new.html.erb
<h3>投稿ページ</h3>
<%= form_with model: @post, local: true do |f| %>
  <%= f.text_field :content %>
  <%= f.submit "投稿する" %>
<% end %>

app/views/shared/_header.html.erb
<%= form_with model: current_user, local: true do |f|%>
  <% if user_signed_in? %>
    <ul>
      <li><%= link_to "#{current_user.name}さん", user_path(current_user.id) %></li>
      <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
    </ul>
  <% else %>
    <ul>
      <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
      <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    </ul>
  <% end %>
<% end %>

app/views/shared/_stats.html.erb
<div>
  <a href="<%= following_user_path(@user) %>">
    <strong id="following">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_destroy.html.erb
<%= form_with model: current_user, url: user_path(current_user), method: :delete, local: true do |f|%>
  <%= f.submit "Accout Delete" %>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_friends.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_friends.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h2>Edit Account</h2>
<h5>アカウントの編集</h5>

<div>
  <%= form_with model: current_user, local: true do |f|%>
    <%= f.label :name %>
    <%= f.text_area :name, autofocus: true %>
    <%= f.submit "Update" %>
  <% end %>
</div>

<%= render 'users/destroy' %>
<%= link_to "マイページに戻る", :back %>

app/views/users/show.html.erb
<h3><%= @user.name %></h3>

<%= form_with model: @user, local: true do |f|%>
  <section>
    <%= render 'shared/stats' %>
  </section>
  <% if signed_in? current_user == @user %>
  <% else %>
    <%= link_to "アカウント情報編集", edit_user_path(:user_id) %>
  <% end %>

  <% if signed_in? current_user == @user %>
    <% if current_user.following?(@user) %>
      <%= render 'unfollow' %>
    <% else %>
      <%= render 'follow' %>
    <% end %>
  <% end %>
<% end %>

app/views/users/show_follow.html.erb
<div>
  <section>
    <%= render 'shared/stats' %>
    <% if @users.any? %>
      <div>
        <% @users.each do |user| %>
          <%= link_to @user.name, user_path(user.id) %>
        <% end %>
      </div>
    <% end %>
  </section>
</div>